name: bit_dev_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_statusbarcolor: ^0.2.1
  flutter_swiper: ^1.1.6
  provider: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
  - static/images/home/
  - static/images/user/
#  fonts:
#    - family: Iconfont
#      fonts:
#          - asset: static/fonts/iconfont.ttf

  fonts:
    - family: Iconfont
      fonts:
       - asset: static/fonts/iconfont.ttf
  
